Repository effective-tech-interview/effective-tech-interview-be, pull requests merged in 2023-03, with the labels that each got.

#13 feat: access token 재발급 기능 구현
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/error/RefreshTokenValidationException.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: enhancement

#14 refactor: exception 디렉토리 이름 변경
  src/main/java/com/sparcs/teamf/api/auth/exception/RefreshTokenValidationException.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/EmailRequestRequiredException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/UnverifiedEmailException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/VerificationCodeMismatchException.java
  src/main/java/com/sparcs/teamf/api/emailauth/service/EmailAuthService.java
  src/main/java/com/sparcs/teamf/api/member/exception/DuplicateEmailException.java
  src/main/java/com/sparcs/teamf/api/member/exception/MemberNotFoundException.java
  src/main/java/com/sparcs/teamf/api/signup/exception/PasswordMismatchException.java
  src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
Labels: refactor

#15 feat: swagger api response 추가
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/maincategory/controller/MainCategoryController.java
  src/main/java/com/sparcs/teamf/api/midcategory/controller/MidCategoryController.java
  src/main/java/com/sparcs/teamf/api/signup/controller/SignupController.java
Labels: documentation

#16 refactor: 인증 관련 내부 로직 변경
  src/main/java/com/sparcs/teamf/api/auth/jwt/JwtFilter.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
Labels: refactor

#17 feat: access token 재발급 기능 구현 및 인증 로직 리팩토링 배포
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/exception/RefreshTokenValidationException.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/JwtFilter.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/EmailRequestRequiredException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/UnverifiedEmailException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/VerificationCodeMismatchException.java
  src/main/java/com/sparcs/teamf/api/emailauth/service/EmailAuthService.java
  src/main/java/com/sparcs/teamf/api/maincategory/controller/MainCategoryController.java
  src/main/java/com/sparcs/teamf/api/member/exception/DuplicateEmailException.java
  src/main/java/com/sparcs/teamf/api/member/exception/MemberNotFoundException.java
  src/main/java/com/sparcs/teamf/api/midcategory/controller/MidCategoryController.java
  src/main/java/com/sparcs/teamf/api/signup/controller/SignupController.java
  src/main/java/com/sparcs/teamf/api/signup/exception/PasswordMismatchException.java
  src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: enhancement

#19 fix: 예외 처리 및 상태 코드 변경
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/EmailRequestRequiredException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/UnverifiedEmailException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/VerificationCodeMismatchException.java
  src/main/java/com/sparcs/teamf/api/error/handler/GlobalExceptionHandler.java
  src/main/java/com/sparcs/teamf/api/signup/controller/SignupController.java
  src/main/java/com/sparcs/teamf/api/signup/exception/PasswordMismatchException.java
Labels: refactor

#20 fix: 예외 처리 및 상태 코드 변경 배포
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/EmailRequestRequiredException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/UnverifiedEmailException.java
  src/main/java/com/sparcs/teamf/api/emailauth/exception/VerificationCodeMismatchException.java
  src/main/java/com/sparcs/teamf/api/error/handler/GlobalExceptionHandler.java
  src/main/java/com/sparcs/teamf/api/signup/controller/SignupController.java
  src/main/java/com/sparcs/teamf/api/signup/exception/PasswordMismatchException.java
Labels: refactor

#24 refactor: security 필터 체인 변경 및 api response schema 설정
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
Labels: refactor

#25 refactor: security 필터 체인 변경 및 api response schema 설정 배포
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
Labels: refactor

#28 feat: redis 의존성 테스트
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/com/sparcs/teamf/common/config/RedisRepositoryConfig.java
  src/main/java/com/sparcs/teamf/sampleredis/Person.java
  src/main/java/com/sparcs/teamf/sampleredis/PersonRedisRepository.java
  src/main/java/com/sparcs/teamf/sampleredis/SimpleRedisTestController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/java/com/sparcs/teamf/RedisRepositoryTest.java
  src/test/java/com/sparcs/teamf/TeamfApplicationTests.java
  src/test/resources/application.yml
Labels: enhancement

#27 feat: 멤버 프로필 기능 구현
  src/main/java/com/sparcs/teamf/api/auth/dto/EffectiveMember.java
  src/main/java/com/sparcs/teamf/api/member/controller/MemberController.java
  src/main/java/com/sparcs/teamf/api/member/dto/MemberProfileResponse.java
  src/main/java/com/sparcs/teamf/api/member/service/MemberService.java
Labels: enhancement

#30 feat: 인증 없이 토큰 주는 api 추가
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/dto/FreeTokenDto.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
Labels: enhancement

#32 feat: 로그아웃 기능을 작성했어요
  src/main/java/com/sparcs/teamf/api/auth/config/SecurityConfig.java
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/error/handler/GlobalExceptionHandler.java
  src/main/java/com/sparcs/teamf/common/config/RestTemplateConfig.java
  src/main/java/com/sparcs/teamf/domain/token/UserToken.java
  src/main/java/com/sparcs/teamf/domain/token/UserTokenRepository.java
  src/main/java/com/sparcs/teamf/sampleredis/Person.java
  src/main/java/com/sparcs/teamf/sampleredis/PersonRedisRepository.java
  src/main/java/com/sparcs/teamf/sampleredis/SimpleRedisTestController.java
  src/test/java/com/sparcs/teamf/RedisRepositoryTest.java
Labels: enhancement

#36 feat: page 관련 엔티티 작성
  src/main/java/com/sparcs/teamf/domain/member/Member.java
  src/main/java/com/sparcs/teamf/domain/page/MemberAnswer.java
  src/main/java/com/sparcs/teamf/domain/page/Page.java
  src/main/java/com/sparcs/teamf/domain/page/PageMemberAnswer.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
  src/main/java/com/sparcs/teamf/domain/question/Question.java
Labels: enhancement

#34 fix: redis에 accessToken 저장하여 토큰 검증하도록 변경
  src/main/java/com/sparcs/teamf/api/auth/controller/AuthController.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/JwtFilter.java
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
  src/main/java/com/sparcs/teamf/api/auth/service/AuthService.java
  src/main/java/com/sparcs/teamf/api/error/handler/GlobalExceptionHandler.java
  src/main/java/com/sparcs/teamf/domain/token/AccessToken.java
  src/main/java/com/sparcs/teamf/domain/token/AccessTokenRepository.java
Labels: refactor

#37 feat: querydsl 세팅 완료
  build.gradle
  src/main/java/com/sparcs/teamf/common/config/QuerydslConfig.java
Labels: enhancement

#38 feat: 회원 탈퇴 기능 구현
  src/main/java/com/sparcs/teamf/api/member/controller/MemberController.java
  src/main/java/com/sparcs/teamf/api/member/service/MemberService.java
  src/main/java/com/sparcs/teamf/domain/emailauth/EmailAuthRepository.java
  src/main/java/com/sparcs/teamf/domain/member/Member.java
  src/main/java/com/sparcs/teamf/domain/member/MemberRepository.java
Labels: enhancement

#39 refactor: page 관련 엔티티 수정
  src/main/java/com/sparcs/teamf/domain/page/MemberAnswer.java
  src/main/java/com/sparcs/teamf/domain/page/MemberAnswerRepository.java
  src/main/java/com/sparcs/teamf/domain/page/Page.java
  src/main/java/com/sparcs/teamf/domain/page/PageMemberAnswer.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestionRepository.java
  src/main/java/com/sparcs/teamf/domain/page/PageRepository.java
Labels: refactor

#40 feat: 페이지 질문 리스트 조회 기능 구현
  src/main/java/com/sparcs/teamf/api/question/controller/PageQuestionController.java
  src/main/java/com/sparcs/teamf/api/question/dto/QuestionResponse.java
  src/main/java/com/sparcs/teamf/api/question/dto/QuestionsResponse.java
  src/main/java/com/sparcs/teamf/api/question/exception/PageNotFountException.java
  src/main/java/com/sparcs/teamf/api/question/exception/PageOwnerMismatchException.java
  src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
  src/main/java/com/sparcs/teamf/domain/gpt/Gpt.java
  src/main/java/com/sparcs/teamf/domain/member/Member.java
  src/main/java/com/sparcs/teamf/domain/member/MemberRepository.java
  src/main/java/com/sparcs/teamf/domain/page/Page.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestionRepository.java
  src/main/java/com/sparcs/teamf/gpt/GptWrapper.java
Labels: enhancement

#42 feat: 멤버 답변 저장 기능 구현
  src/main/java/com/sparcs/teamf/api/answer/controller/PageAnswerController.java
  src/main/java/com/sparcs/teamf/api/answer/dto/SaveMemberAnswerRequest.java
  src/main/java/com/sparcs/teamf/api/answer/exception/PageQuestionNotFoundException.java
  src/main/java/com/sparcs/teamf/api/answer/service/PageAnswerService.java
  src/main/java/com/sparcs/teamf/api/question/exception/PageQuestionMismatchException.java
  src/main/java/com/sparcs/teamf/domain/page/MemberAnswer.java
  src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
Labels: enhancement

#45 fix: 페이지 API 저장 로직 변경 배포
  src/main/java/com/sparcs/teamf/api/question/controller/PageQuestionController.java
  src/main/java/com/sparcs/teamf/api/question/dto/PageResponse.java
  src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
Labels: refactor

#46 feat: 401 에러시 예외 처리 body 추가
  .github/workflows/deploy.yml
  src/main/java/com/sparcs/teamf/api/auth/jwt/JwtAuthenticationEntryPoint.java
Labels: enhancement

#47 fix: 배포 환경에서 show sql false 로 변경
  src/main/resources/application-dev.yml
Labels: bug

#49 fix: statuscode 200 문제 해결
  src/main/java/com/sparcs/teamf/api/auth/jwt/JwtAuthenticationEntryPoint.java
Labels: bug

#51 chore: jwt 파싱 실패시 error 트래킹 제거
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
Labels: enhancement

#52 fix: refresh token 찾는 위치가 accesstoken 위치인 부분 수정
  src/main/java/com/sparcs/teamf/api/auth/jwt/TokenProvider.java
Labels: bug

#56 feat: 이메일 발송 계정 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement
